githubRepoOwner: inigolabs
githubRepoName: inigo-js
githubHost: github.com
requireChecks: false
requireApproval: false
githubRemote: origin
githubBranch: master
remoteBranches: []
mergeMethod: rebase
